### ISSUE TITLE
udev dependency missing

### ISSUE THREAD

**Issue by phpsystems** [f-secure-foundry/usbarmory-debian-base_image#26]
Hi,

For the docker image, you may need to add the dependency for udev, as udevadm was not installed in my image.

**Comment by phpsystems** [comment]
Also, could do with:

mknod /dev/loop0 b 7 0

These are on PhotonOS docker, if that makes any difference.

**Comment by andrejro** [comment]
We can explicitly include udev in the required packages, but not sure why in your case udev is not installed by default.

**Comment by andrejro** [comment]
Added udev package. Check commit f95fcb2908746c16f9c1f6e91450a925baa3ef5d.
Thanks
