### ISSUE TITLE
HSM kernel modules release

### ISSUE THREAD

**Issue by Silur** [f-secure-foundry/usbarmory-debian-base_image#27]
Would be nice to have a precompiled release that has SCC2/DCP/CAAM modules built and enabled for MKII

**Comment by abarisani** [comment]
The SCC2 is present on the Mk I, not the Mk II.

The CAAM is present only on [variants for custom bulk orders](https://github.com/f-secure-foundry/usbarmory/wiki/Hardware-security-features-(Mk-II)#imx6ulimx6ulz-system-on-chip).

The DCP driver is already included in our Debian release.
