### ISSUE TITLE
Latest release (buster) still has stretch sources.list

### ISSUE THREAD

**Issue by jonZlotnik** [f-secure-foundry/usbarmory-debian-base_image#30]

**Comment by andrejro** [comment]
Fixing this in a new release. Will be published today.
Will add a note to the 20200406 Release Note explaining how to fix that.
Thanks

**Comment by jonZlotnik** [comment]
Wow, sick response time!!

**Comment by andrejro** [comment]
Fixed in https://github.com/f-secure-foundry/usbarmory-debian-base_image/commit/c4de032f448f7033296e00191ba717697e885173
The fixed binary image is also available: https://github.com/f-secure-foundry/usbarmory-debian-base_image/releases/tag/20200408
