### ISSUE TITLE
Possible regression in commit 19fd662

### ISSUE THREAD

**Issue by evilaliv3** [f-secure-foundry/usbarmory-debian-base_image#37]
Its seems that commit https://github.com/f-secure-foundry/usbarmory-debian-base_image/commit/19fd662f3df265e7390104ea1885b936c58810c3 contains a regression.

The use of ```$``` symbol within the sudo chroot bash command causes to write corrupted data in /ets/shadow as hash for the ```usbarmory``` password. 

e.g. in my tests it has been written: ```usbarmory:E13Mtqs3Fmark-twovaDyPBE6o/Ey0sbyIh5/8tbxBuSiRlLr5rai5M7C70S22HDwBvtu2XOFsvmgRMu.tPdyY6ZcjRrbraF.dWL51:18375:0:99999:7:::``` where you can read ```mark-two```

\cc @abarisani

**Comment by andrejro** [comment]
Fixed in ab396bdf36b8e9d92709985dd8dae4242b7f0970
Thanks.
