### ISSUE TITLE
Routing Internet access into Debian

### ISSUE THREAD

**Issue by bernardoaraujor** [f-secure-foundry/usbarmory-debian-base_image#42]
I'm trying to provide internet access to my USB Armory (Debian) from my Ubuntu host.
I'm able to get an SSH shell just fine.

I'm running the [commands from the wiki](https://github.com/f-secure-foundry/usbarmory/wiki/Host-communication#setup--connection-sharing-linux), however I can't `ping 8.8.8.8` from the Armory.

cc @nothingismagick

**Comment by abarisani** [comment]
Is your Internet facing interface named `wlan0` as assumed in the example? Do you have any firewall rules in place that my prevent USB armory traffic?

On Ubuntu the NetworkManager is quite invasive, it would be probably best to use Ubuntu GUI for this.

Something similar to [this](https://askubuntu.com/questions/169473/sharing-connection-to-other-pcs-via-wired-ethernet).

**Comment by andrejro** [comment]
@bernardoaraujor is this issue still present?

**Comment by bernardoaraujor** [comment]
sorry I haven't tried yet.
I'll give some feedback soon

**Comment by bernardoaraujor** [comment]
issue solved.
solution was documented by @elenaf9 at https://github.com/iotaledger/stronghold.rs/issues/55#issuecomment-744405822
