### ISSUE TITLE
Where can the new public key be retrieved for the package repo?

### ISSUE THREAD

**Issue by assarbad** [f-secure-foundry/usbarmory-debian-base_image#49]
Hi, when I attempt to look up `keys.gnupg.net` it fails and [your instructions](https://github.com/f-secure-foundry/usbarmory-debian-base_image#pre-requisites) also still reference the old key. But it appears a key change happened (or, perhaps less likely) your repository got compromised.

Where can one find the transition notice and the new public key?

Exact error is:

```
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://f-secure-foundry.github.io/debian stable Rel
ease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A81E36CAA33925BE
W: Failed to fetch https://f-secure-foundry.github.io/debian/dists/stable/Release.gpg  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A81E36CAA33925BE
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

Thanks,

Oliver

PS: I realize the instructions reference the _creation_ of a Debian image, but still.
PPS: I also peeked into the latest available prebuilt image and got the following two public keys shown from the `/etc/apt/trusted.gpg` which I copied out of there. Neither matched the `A81E36CAA33925BE` with which the Release.gpg appears to be signed.

```
$ gpg --homedir $(pwd)/.gnupg -k
gpg: /data/oliver/usbarmory/.gnupg/trustdb.gpg: trustdb created
/data/oliver/usbarmory/.gnupg/pubring.gpg
-----------------------------------------
pub   rsa4096 2021-05-09 [SC] [expires: 2024-05-08]
      BDE162F4702015888046AE02EA178C32AB5654CE
uid           [ unknown] Andrej Rosano <andrej.rosano@f-secure.com>
sub   rsa4096 2021-05-09 [E] [expires: 2024-05-08]
sub   rsa4096 2021-05-09 [S] [expires: 2024-05-08]

pub   dsa1024 2003-12-02 [SC] [expires: 2023-04-08]
      0A76074A02CDE989CE7FAC3FDA47578E864C9B9E
uid           [ unknown] Andrea Barisani <andrea@inversepath.com>
uid           [ unknown] Andrea Barisani <andrea.barisani@f-secure.com>
sub   rsa2048 2018-04-09 [S] [expires: 2023-04-08]
sub   rsa2048 2018-04-09 [E] [expires: 2023-04-08]
```

**Comment by assarbad** [comment]
Meanwhile found https://github.com/f-secure-foundry/f-secure-foundry.github.io/commit/4f6dbd401dee82a1ae4342241570c3b3f3e5b3bd ... but I still can't make sense of the discrepancy.

**Comment by eduncan911** [comment]
I believe the `Makefile` pulls the latest key on each build (it's part of the CICD here).  Does this help?

https://github.com/f-secure-foundry/usbarmory-debian-base_image/blob/d62df123b39af7b64c44946ee526581a52931dea/Makefile#L114-L115

**Comment by andrejro** [comment]
One of the keys used to sign the Debian packages in the f-secure-foundry.github.io expired. You need to
add the new key:
```
wget https://f-secure-foundry.github.io/keys/gpg-andrej.asc -O - | apt-key add
```
This was also mentioned on the following mailing list post: https://groups.google.com/g/usbarmory/c/ExmqjGaGzFo
